# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
     - uses : actions/checkout@v2

     - name : Set up JDK 1.8
       uses : actions/setup-java@v1
       with :
         java-version: 1.8

      - name : Run the lint
        uses : ./gradlew lintDebug

      # publishing the report
      - name : Upload html test report
        uses : actions/upload-artifact@v2
        with:
          name : lint.html
          path : app/build/reports/lint-results-debug.html
